## Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

# Import pandas and read the charity_data.csv from the provided cloud URL.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [2]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df = application_df.drop(['EIN', 'NAME'], axis=1)

In [3]:
# Determine the number of unique values in each column.
application_df.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [4]:
# Look at APPLICATION_TYPE value counts to identify and replace with "Other"
application_df['APPLICATION_TYPE'].value_counts()

APPLICATION_TYPE
T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: count, dtype: int64

In [5]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = ['T9','T13','T12','T2','T25','T14','T29','T15','T17']

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure replacement was successful
application_df['APPLICATION_TYPE'].value_counts()

APPLICATION_TYPE
T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: count, dtype: int64

In [6]:
# Look at CLASSIFICATION value counts to identify and replace with "Other"
value_counts = application_df['CLASSIFICATION'].value_counts()
value_counts

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: count, Length: 71, dtype: int64

In [7]:
# You may find it helpful to look at CLASSIFICATION value counts >1
filtered_values = value_counts[value_counts > 1]
filtered_values

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: count, dtype: int64

In [8]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace = value_counts[value_counts < 1000].index.tolist()

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure replacement was successful
application_df['CLASSIFICATION'].value_counts()

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: count, dtype: int64

In [9]:
application_df.head()

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [10]:
# Convert categorical data to numeric with `pd.get_dummies`
columns_to_encode = ['APPLICATION_TYPE', 'AFFILIATION', 'CLASSIFICATION', 'USE_CASE', 'ORGANIZATION', 'INCOME_AMT', 'SPECIAL_CONSIDERATIONS']
df_encoded = pd.get_dummies(application_df, columns=columns_to_encode)

df_encoded.nunique()

STATUS                             2
ASK_AMT                         8747
IS_SUCCESSFUL                      2
APPLICATION_TYPE_Other             2
APPLICATION_TYPE_T10               2
APPLICATION_TYPE_T19               2
APPLICATION_TYPE_T3                2
APPLICATION_TYPE_T4                2
APPLICATION_TYPE_T5                2
APPLICATION_TYPE_T6                2
APPLICATION_TYPE_T7                2
APPLICATION_TYPE_T8                2
AFFILIATION_CompanySponsored       2
AFFILIATION_Family/Parent          2
AFFILIATION_Independent            2
AFFILIATION_National               2
AFFILIATION_Other                  2
AFFILIATION_Regional               2
CLASSIFICATION_C1000               2
CLASSIFICATION_C1200               2
CLASSIFICATION_C2000               2
CLASSIFICATION_C2100               2
CLASSIFICATION_C3000               2
CLASSIFICATION_Other               2
USE_CASE_CommunityServ             2
USE_CASE_Heathcare                 2
USE_CASE_Other                     2
USE_CASE_Preservation              2
USE_CASE_ProductDev                2
ORGANIZATION_Association           2
ORGANIZATION_Co-operative          2
ORGANIZATION_Corporation           2
ORGANIZATION_Trust                 2
INCOME_AMT_0                       2
INCOME_AMT_1-9999                  2
INCOME_AMT_10000-24999             2
INCOME_AMT_100000-499999           2
INCOME_AMT_10M-50M                 2
INCOME_AMT_1M-5M                   2
INCOME_AMT_25000-99999             2
INCOME_AMT_50M+                    2
INCOME_AMT_5M-10M                  2
SPECIAL_CONSIDERATIONS_N           2
SPECIAL_CONSIDERATIONS_Y           2
dtype: int64

In [11]:
df_encoded

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
1,1,108590,1,False,False,False,True,False,False,False,...,True,False,False,False,False,False,False,False,True,False
2,1,5000,0,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,True,False
3,1,6692,1,False,False,False,True,False,False,False,...,False,True,False,False,False,False,False,False,True,False
4,1,142590,1,False,False,False,True,False,False,False,...,False,False,True,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,1,5000,0,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,True,False
34295,1,5000,0,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,True,False
34296,1,5000,0,False,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,True,False
34297,1,5000,1,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,True,False
34298,1,36500179,0,False,False,False,True,False,False,False,...,False,False,False,False,True,False,False,False,True,False

In [12]:
# Split our preprocessed data into our features and target arrays
y = df_encoded['IS_SUCCESSFUL']
X = df_encoded.drop(columns='IS_SUCCESSFUL')

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

In [13]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [14]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
input_features = len(X_train.columns)
hidden_layer1 = 8
hidden_layer2 = 8
hidden_layer3 = 8

nn = tf.keras.models.Sequential()

# Input layer
nn.add(tf.keras.layers.Input(shape=[input_features]))

# First hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_layer1, activation="relu"))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_layer2, activation="tanh"))

# Third hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_layer3, activation="tanh"))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (None, 8)                   │             352 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 8)                   │              72 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ (None, 8)                   │              72 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_3 (Dense)                      │ (None, 1)                   │               9 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 505 (1.97 KB)

 Trainable params: 505 (1.97 KB)

 Non-trainable params: 0 (0.00 B)

In [15]:
# Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy", "precision", "recall"])

In [16]:
# Train the model
fit_model = nn.fit(X_train_scaled, y_train, epochs=100)

Epoch 1/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 973us/step - accuracy: 0.6202 - loss: 0.6464 - precision: 0.6269 - recall: 0.7286
Epoch 2/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 853us/step - accuracy: 0.7204 - loss: 0.5683 - precision: 0.7232 - recall: 0.7738
Epoch 3/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 937us/step - accuracy: 0.7187 - loss: 0.5623 - precision: 0.7212 - recall: 0.7711
Epoch 4/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 826us/step - accuracy: 0.7265 - loss: 0.5623 - precision: 0.7281 - recall: 0.7778
Epoch 5/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 810us/step - accuracy: 0.7362 - loss: 0.5496 - precision: 0.7363 - recall: 0.7932
Epoch 6/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 854us/step - accuracy: 0.7307 - loss: 0.5513 - precision: 0.7312 - recall: 0.7820
Epoch 7/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 838us/step - accuracy: 0.7327 - loss: 0.5526 - precision: 0.7350 - recall: 0.7783
Epoch 8/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 941us/step - accuracy: 0.7327 - loss: 0.5494 - precision: 0.7317 - recall: 0.7883
Epoch 9/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 840us/step - accuracy: 0.7290 - loss: 0.5504 - precision: 0.7260 - recall: 0.7875
Epoch 10/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 841us/step - accuracy: 0.7331 - loss: 0.5482 - precision: 0.7353 - recall: 0.7856
Epoch 11/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 826us/step - accuracy: 0.7375 - loss: 0.5457 - precision: 0.7321 - recall: 0.7997
Epoch 12/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 897us/step - accuracy: 0.7352 - loss: 0.5478 - precision: 0.7378 - recall: 0.7853
Epoch 13/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 847us/step - accuracy: 0.7298 - loss: 0.5532 - precision: 0.7258 - recall: 0.7916
Epoch 14/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 885us/step - accuracy: 0.7325 - loss: 0.5498 - precision: 0.7315 - recall: 0.7861
Epoch 15/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 935us/step - accuracy: 0.7335 - loss: 0.5456 - precision: 0.7291 - recall: 0.7926
Epoch 16/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 813us/step - accuracy: 0.7308 - loss: 0.5491 - precision: 0.7299 - recall: 0.7860
Epoch 17/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 840us/step - accuracy: 0.7359 - loss: 0.5438 - precision: 0.7325 - recall: 0.7988
Epoch 18/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 872us/step - accuracy: 0.7329 - loss: 0.5489 - precision: 0.7295 - recall: 0.7904
Epoch 19/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 963us/step - accuracy: 0.7351 - loss: 0.5447 - precision: 0.7366 - recall: 0.7877
Epoch 20/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 867us/step - accuracy: 0.7313 - loss: 0.5496 - precision: 0.7281 - recall: 0.7931
Epoch 21/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 870us/step - accuracy: 0.7376 - loss: 0.5437 - precision: 0.7357 - recall: 0.7967
Epoch 22/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 844us/step - accuracy: 0.7372 - loss: 0.5441 - precision: 0.7362 - recall: 0.7923
Epoch 23/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 922us/step - accuracy: 0.7334 - loss: 0.5468 - precision: 0.7283 - recall: 0.7939
Epoch 24/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 813us/step - accuracy: 0.7338 - loss: 0.5428 - precision: 0.7300 - recall: 0.7939
Epoch 25/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 945us/step - accuracy: 0.7315 - loss: 0.5499 - precision: 0.7252 - recall: 0.7934
Epoch 26/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 980us/step - accuracy: 0.7324 - loss: 0.5475 - precision: 0.7284 - recall: 0.7922
Epoch 27/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 897us/step - accuracy: 0.7292 - loss: 0.5490 - precision: 0.7246 - recall: 0.7931
Epoch 28/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7378 - loss: 0.5415 - precision: 0.7381 - recall: 0.7930
Epoch 29/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 869us/step - accuracy: 0.7317 - loss: 0.5477 - precision: 0.7267 - recall: 0.7969
Epoch 30/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 863us/step - accuracy: 0.7356 - loss: 0.5434 - precision: 0.7263 - recall: 0.7951
Epoch 31/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 918us/step - accuracy: 0.7326 - loss: 0.5455 - precision: 0.7296 - recall: 0.7972
Epoch 32/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 872us/step - accuracy: 0.7350 - loss: 0.5439 - precision: 0.7302 - recall: 0.7983
Epoch 33/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 834us/step - accuracy: 0.7414 - loss: 0.5383 - precision: 0.7359 - recall: 0.8013
Epoch 34/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 962us/step - accuracy: 0.7381 - loss: 0.5402 - precision: 0.7325 - recall: 0.8097
Epoch 35/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 858us/step - accuracy: 0.7370 - loss: 0.5405 - precision: 0.7292 - recall: 0.7965
Epoch 36/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 963us/step - accuracy: 0.7324 - loss: 0.5461 - precision: 0.7249 - recall: 0.8050
Epoch 37/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 928us/step - accuracy: 0.7218 - loss: 0.5568 - precision: 0.7193 - recall: 0.7879
Epoch 38/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 851us/step - accuracy: 0.7336 - loss: 0.5438 - precision: 0.7262 - recall: 0.8038
Epoch 39/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 868us/step - accuracy: 0.7377 - loss: 0.5425 - precision: 0.7359 - recall: 0.7998
Epoch 40/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 832us/step - accuracy: 0.7387 - loss: 0.5415 - precision: 0.7349 - recall: 0.7977
Epoch 41/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 829us/step - accuracy: 0.7388 - loss: 0.5413 - precision: 0.7336 - recall: 0.8078
Epoch 42/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 909us/step - accuracy: 0.7336 - loss: 0.5447 - precision: 0.7313 - recall: 0.7898
Epoch 43/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 973us/step - accuracy: 0.7342 - loss: 0.5436 - precision: 0.7299 - recall: 0.8020
Epoch 44/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 900us/step - accuracy: 0.7356 - loss: 0.5437 - precision: 0.7332 - recall: 0.8021
Epoch 45/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 964us/step - accuracy: 0.7393 - loss: 0.5411 - precision: 0.7356 - recall: 0.8058
Epoch 46/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 831us/step - accuracy: 0.7412 - loss: 0.5410 - precision: 0.7317 - recall: 0.8089
Epoch 47/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 917us/step - accuracy: 0.7321 - loss: 0.5469 - precision: 0.7286 - recall: 0.7846
Epoch 48/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 865us/step - accuracy: 0.7323 - loss: 0.5474 - precision: 0.7275 - recall: 0.7997
Epoch 49/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 897us/step - accuracy: 0.7339 - loss: 0.5439 - precision: 0.7315 - recall: 0.8030
Epoch 50/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 865us/step - accuracy: 0.7360 - loss: 0.5442 - precision: 0.7325 - recall: 0.7965
Epoch 51/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 928us/step - accuracy: 0.7370 - loss: 0.5420 - precision: 0.7274 - recall: 0.8029
Epoch 52/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 817us/step - accuracy: 0.7343 - loss: 0.5444 - precision: 0.7251 - recall: 0.8052
Epoch 53/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 876us/step - accuracy: 0.7387 - loss: 0.5413 - precision: 0.7317 - recall: 0.8054
Epoch 54/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 808us/step - accuracy: 0.7382 - loss: 0.5388 - precision: 0.7330 - recall: 0.8063
Epoch 55/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 912us/step - accuracy: 0.7349 - loss: 0.5420 - precision: 0.7290 - recall: 0.8011
Epoch 56/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 885us/step - accuracy: 0.7336 - loss: 0.5455 - precision: 0.7247 - recall: 0.8045
Epoch 57/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 896us/step - accuracy: 0.7385 - loss: 0.5424 - precision: 0.7328 - recall: 0.8103
Epoch 58/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 878us/step - accuracy: 0.7356 - loss: 0.5408 - precision: 0.7287 - recall: 0.8005
Epoch 59/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 802us/step - accuracy: 0.7380 - loss: 0.5418 - precision: 0.7337 - recall: 0.7962
Epoch 60/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 928us/step - accuracy: 0.7355 - loss: 0.5424 - precision: 0.7282 - recall: 0.8061
Epoch 61/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 851us/step - accuracy: 0.7287 - loss: 0.5469 - precision: 0.7219 - recall: 0.7925
Epoch 62/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 916us/step - accuracy: 0.7334 - loss: 0.5429 - precision: 0.7249 - recall: 0.8082
Epoch 63/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7356 - loss: 0.5417 - precision: 0.7285 - recall: 0.8036
Epoch 64/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 827us/step - accuracy: 0.7306 - loss: 0.5458 - precision: 0.7252 - recall: 0.7936
Epoch 65/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 891us/step - accuracy: 0.7351 - loss: 0.5431 - precision: 0.7299 - recall: 0.8093
Epoch 66/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 940us/step - accuracy: 0.7298 - loss: 0.5497 - precision: 0.7232 - recall: 0.7963
Epoch 67/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 823us/step - accuracy: 0.7397 - loss: 0.5416 - precision: 0.7342 - recall: 0.8075
Epoch 68/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 892us/step - accuracy: 0.7347 - loss: 0.5434 - precision: 0.7277 - recall: 0.8016
Epoch 69/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 881us/step - accuracy: 0.7358 - loss: 0.5420 - precision: 0.7285 - recall: 0.8003
Epoch 70/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 862us/step - accuracy: 0.7391 - loss: 0.5354 - precision: 0.7309 - recall: 0.8063
Epoch 71/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 932us/step - accuracy: 0.7338 - loss: 0.5446 - precision: 0.7291 - recall: 0.7997
Epoch 72/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 940us/step - accuracy: 0.7335 - loss: 0.5425 - precision: 0.7264 - recall: 0.7992
Epoch 73/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7355 - loss: 0.5425 - precision: 0.7258 - recall: 0.8003
Epoch 74/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 837us/step - accuracy: 0.7342 - loss: 0.5455 - precision: 0.7246 - recall: 0.8098
Epoch 75/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 940us/step - accuracy: 0.7362 - loss: 0.5428 - precision: 0.7307 - recall: 0.8039
Epoch 76/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 911us/step - accuracy: 0.7327 - loss: 0.5449 - precision: 0.7255 - recall: 0.8003
Epoch 77/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 953us/step - accuracy: 0.7341 - loss: 0.5442 - precision: 0.7254 - recall: 0.8042
Epoch 78/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7329 - loss: 0.5431 - precision: 0.7279 - recall: 0.7897
Epoch 79/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 815us/step - accuracy: 0.7360 - loss: 0.5416 - precision: 0.7268 - recall: 0.8043
Epoch 80/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 912us/step - accuracy: 0.7369 - loss: 0.5430 - precision: 0.7320 - recall: 0.8048
Epoch 81/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 934us/step - accuracy: 0.7348 - loss: 0.5432 - precision: 0.7330 - recall: 0.8019
Epoch 82/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 952us/step - accuracy: 0.7426 - loss: 0.5386 - precision: 0.7352 - recall: 0.8098
Epoch 83/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 915us/step - accuracy: 0.7400 - loss: 0.5393 - precision: 0.7349 - recall: 0.8069
Epoch 84/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 981us/step - accuracy: 0.7370 - loss: 0.5402 - precision: 0.7325 - recall: 0.7965
Epoch 85/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 867us/step - accuracy: 0.7362 - loss: 0.5422 - precision: 0.7288 - recall: 0.8064
Epoch 86/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 860us/step - accuracy: 0.7380 - loss: 0.5398 - precision: 0.7300 - recall: 0.8079
Epoch 87/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 981us/step - accuracy: 0.7343 - loss: 0.5415 - precision: 0.7265 - recall: 0.8081
Epoch 88/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 977us/step - accuracy: 0.7374 - loss: 0.5390 - precision: 0.7323 - recall: 0.7979
Epoch 89/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 950us/step - accuracy: 0.7358 - loss: 0.5419 - precision: 0.7303 - recall: 0.8053
Epoch 90/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 934us/step - accuracy: 0.7347 - loss: 0.5457 - precision: 0.7262 - recall: 0.8076
Epoch 91/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 952us/step - accuracy: 0.7308 - loss: 0.5465 - precision: 0.7239 - recall: 0.8037
Epoch 92/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 928us/step - accuracy: 0.7401 - loss: 0.5380 - precision: 0.7329 - recall: 0.8095
Epoch 93/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 925us/step - accuracy: 0.7384 - loss: 0.5379 - precision: 0.7298 - recall: 0.8136
Epoch 94/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 945us/step - accuracy: 0.7406 - loss: 0.5388 - precision: 0.7364 - recall: 0.8008
Epoch 95/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 926us/step - accuracy: 0.7402 - loss: 0.5365 - precision: 0.7328 - recall: 0.8088
Epoch 96/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 942us/step - accuracy: 0.7393 - loss: 0.5379 - precision: 0.7323 - recall: 0.8162
Epoch 97/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 912us/step - accuracy: 0.7395 - loss: 0.5395 - precision: 0.7326 - recall: 0.8083
Epoch 98/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 955us/step - accuracy: 0.7326 - loss: 0.5452 - precision: 0.7275 - recall: 0.8019
Epoch 99/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 926us/step - accuracy: 0.7360 - loss: 0.5440 - precision: 0.7259 - recall: 0.8061
Epoch 100/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 881us/step - accuracy: 0.7357 - loss: 0.5383 - precision: 0.7255 - recall: 0.8044

In [17]:
# Evaluate the model using the test data
model_loss, model_accuracy, model_precision, model_recall = nn.evaluate(X_test_scaled, y_test, verbose=2)
print(f"Accuracy: {model_accuracy}, Loss: {model_loss}, Precision: {model_precision}, Recall: {model_recall} ")

268/268 - 1s - 2ms/step - accuracy: 0.7279 - loss: 0.5535 - precision: 0.7115 - recall: 0.8173
Accuracy: 0.7279300093650818, Loss: 0.5534540414810181, Precision: 0.7114905118942261, Recall: 0.8173204064369202

In [18]:
# Export our model to HDF5 file
nn.save("NN_3.h5")

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.